default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
      scheme: "LumosApp",
      devices: ["iPhone 15"]
    )
  end

  desc "Archive and export IPA (template)"
  lane :build_release do
    gym(
      scheme: "LumosApp",
      export_options: "./ios/config/ExportOptions.plist"
    )
  end
end
